on: push

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        installation_id: 25232613
        app_id: 194811
        repository: lwille/shared-workflows
        private_key: ${{ secrets.GH_APP_SECRET_KEY }}
    - uses: actions/checkout@v2
      with:
        repository: lwille/shared-workflows
        path: .shared-actions
        token: ${{ steps.generate_token.outputs.token }}
        ref: main
    - run: tree -a
    - uses: ./.shared-actions/.github/workflows/shared.yml

